[project]
name = "amuse-evtwin"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["evtwin/**/*.py", "evtwin/data/"]
exclude = [
    "evtwin/packages",
    "evtwin/support",
    "evtwin/src",
    "evtwin/tests"
    ]
artifacts = ["evtwin/evtwin_worker"]

[tool.hatch.build.targets.wheel.sources]
"evtwin" = "amuse/community/evtwin"

[tool.pytest.ini_options]
pythonpath = ["evtwin/tests/", "../../../../../tests"]

testpaths = ["evtwin/tests"]

