[project]
name = "amuse-huayno"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["huayno/**/*.py"]
exclude = [
    "huayno/packages",
    "huayno/support",
    "huayno/src",
    "huayno/tests"
    ]
artifacts = ["huayno/huayno_worker"]

[tool.hatch.build.targets.wheel.sources]
"huayno" = "amuse/community/huayno"

[tool.pytest.ini_options]
pythonpath = ["huayno/tests/", "../../../../../tests"]

testpaths = ["huayno/tests"]

addopts = "-k 'not opencl and not openmp'"

