[project]
name = "amuse-ph4-sapporo"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework",
    "amuse-ph4"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["ph4"]
exclude = ["ph4/*"]
artifacts = ["ph4/ph4_sapporo_worker"]

[tool.hatch.build.targets.wheel.sources]
"ph4" = "amuse/community/ph4"

[tool.pytest.ini_options]
pythonpath = ["ph4/tests/", "../../../../../tests"]

testpaths = ["ph4/tests"]

addopts = "-k gpu"

