[project]
name = "amuse-mesa-r2208"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["mesa_r2208/**/*.py"]
exclude = [
    "mesa_r2208/packages",
    "mesa_r2208/support",
    "mesa_r2208/src",
    "mesa_r2208/tests"
    ]
artifacts = ["mesa_r2208/mesa_r2208_worker", "mesa_r2208/data"]

[tool.hatch.build.targets.wheel.sources]
"mesa_r2208" = "amuse/community/mesa_r2208"

[tool.pytest.ini_options]
pythonpath = ["mesa_r2208/tests/", "../../../../../tests"]

testpaths = ["mesa_r2208/tests"]

