[project]
name = "amuse-symple"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["symple/**/*.py"]
exclude = [
    "symple/packages",
    "symple/support",
    "symple/src",
    "symple/tests"
    ]
artifacts = ["symple/symple_worker"]

[tool.hatch.build.targets.wheel.sources]
"symple" = "amuse/community/symple"

[tool.pytest.ini_options]
pythonpath = ["symple/tests/", "../../../../../tests"]

testpaths = ["symple/tests"]

# These files are not runnable by pytest
addopts = "--ignore='symple/tests/test.py' --ignore='symple/tests/test_si.py'"

