[build-system]
requires = [
    'amuse-framework>=12.0.0rc3[MPI]',
    'amuse-athena>=12.0.0rc3',
    'amuse-bhtree>=12.0.0rc3',
    'amuse-brutus>=12.0.0rc3',
    'amuse-bse>=12.0.0rc3',
    'amuse-capreole>=12.0.0rc3',
    'amuse-evtwin>=12.0.0rc3',
    'amuse-fastkick>=12.0.0rc3',
    'amuse-fi>=12.0.0rc3',
    'amuse-fractalcluster>=12.0.0rc3',
    'amuse-gadget2>=12.0.0rc3',
    'amuse-galactics>=12.0.0rc3',
    'amuse-galaxia>=12.0.0rc3',
    'amuse-halogen>=12.0.0rc3',
    'amuse-hermite>=12.0.0rc3',
    'amuse-hop>=12.0.0rc3',
    'amuse-huayno>=12.0.0rc3',
    'amuse-kepler>=12.0.0rc3',
    'amuse-kepler-orbiters>=12.0.0rc3',
    'amuse-mameclot>=12.0.0rc3',
    'amuse-mercury>=12.0.0rc3',
    'amuse-mmams>=12.0.0rc3',
    'amuse-ph4>=12.0.0rc3',
    'amuse-seba>=12.0.0rc3',
    'amuse-secularmultiple>=12.0.0rc3',
#    'amuse-simplex>=12.0.0rc3',
    'amuse-smalln>=12.0.0rc3',
    'amuse-sphray>=12.0.0rc3',
    'amuse-sse>=12.0.0rc3',
    'amuse-twobody>=12.0.0rc3',
]
