[build-system]
requires = [
    'amuse-framework[MPI]>=2021.7.0',
    'amuse-athena>=2021.7.0',
    'amuse-bhtree>=2021.7.0',
    'amuse-brutus>=2021.7.0',
    'amuse-bse>=2021.7.0',
    'amuse-capreole>=2021.7.0',
    'amuse-evtwin>=2021.7.0',
    'amuse-fastkick>=2021.7.0',
    'amuse-fi>=2021.7.0',
    'amuse-fractalcluster>=2021.7.0',
    'amuse-gadget2>=2021.7.0',
    'amuse-galactics>=2021.7.0',
    'amuse-galaxia>=2021.7.0',
    'amuse-halogen>=2021.7.0',
    'amuse-hermite>=2021.7.0',
    'amuse-hop>=2021.7.0',
    'amuse-huayno>=2021.7.0',
    'amuse-kepler>=2021.7.0',
    'amuse-kepler-orbiters>=2021.7.0',
    'amuse-mameclot>=2021.7.0',
    'amuse-mercury>=2021.7.0',
    'amuse-mmams>=2021.7.0',
    'amuse-ph4>=2021.7.0',
    'amuse-seba>=2021.7.0',
    'amuse-secularmultiple>=2021.7.0',
    # 'amuse-simplex>=2021.7.0',
    'amuse-smalln>=2021.7.0',
    'amuse-sphray>=2021.7.0',
    'amuse-sse>=2021.7.0',
    'amuse-twobody>=2021.7.0',
]
