[build-system]
requires = [
    'amuse-framework>=13.0.0b3[MPI]',
    'amuse-athena>=13.0.0b3',
    'amuse-bhtree>=13.0.0b3',
    'amuse-brutus>=13.0.0b3',
    'amuse-bse>=13.0.0b3',
    'amuse-capreole>=13.0.0b3',
    'amuse-evtwin>=13.0.0b3',
    'amuse-fastkick>=13.0.0b3',
    'amuse-fi>=13.0.0b3',
    'amuse-fractalcluster>=13.0.0b3',
    'amuse-gadget2>=13.0.0b3',
    'amuse-galactics>=13.0.0b3',
    'amuse-galaxia>=13.0.0b3',
    'amuse-halogen>=13.0.0b3',
    'amuse-hermite>=13.0.0b3',
    'amuse-hop>=13.0.0b3',
    'amuse-huayno>=13.0.0b3',
    'amuse-kepler>=13.0.0b3',
    'amuse-kepler-orbiters>=13.0.0b3',
    'amuse-mameclot>=13.0.0b3',
    'amuse-mercury>=13.0.0b3',
    'amuse-mmams>=13.0.0b3',
    'amuse-ph4>=13.0.0b3',
    'amuse-seba>=13.0.0b3',
    'amuse-secularmultiple>=13.0.0b3',
    # 'amuse-simplex>=13.0.0b3',
    'amuse-smalln>=13.0.0b3',
    'amuse-sphray>=13.0.0b3',
    'amuse-sse>=13.0.0b3',
    'amuse-twobody>=13.0.0b3',
]
