[project]
name = "amuse-etics"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["etics/**/*.py"]
exclude = [
    "etics/packages",
    "etics/support",
    "etics/src",
    "etics/tests"
    ]
artifacts = ["etics/etics_worker"]

[tool.hatch.build.targets.wheel.sources]
"etics" = "amuse/community/etics"

[tool.pytest.ini_options]
pythonpath = ["etics/tests/", "../../../../../tests"]

testpaths = ["etics/tests"]

